# Generated by Django 6.0.4 on 2026-06-29 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_rename_core_integr_key_708abc_idx_core_integr_key_7cc8d4_idx'),
        ('instruments', '0005_alter_instrument_instrument_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nominee_name', models.CharField(blank=True, max_length=100)),
                ('nominee_relation', models.CharField(blank=True, max_length=50)),
                ('policy_type', models.CharField(choices=[('life', 'Life'), ('health', 'Health'), ('vehicle', 'Vehicle'), ('govt_scheme', 'Government Scheme'), ('other', 'Other')], max_length=20)),
                ('policy_subtype', models.CharField(blank=True, max_length=50)),
                ('policy_name', models.CharField(max_length=200)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('insurer_name', models.CharField(blank=True, max_length=200)),
                ('sum_insured', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('premium_frequency', models.CharField(choices=[('annual', 'Annual'), ('half_yearly', 'Half-Yearly'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('single', 'Single Premium'), ('na', 'N/A')], default='annual', max_length=20)),
                ('premium_due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('premium_due_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grace_days', models.PositiveSmallIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_employer_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_family_floater', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(blank=True, choices=[('car', 'Car'), ('two_wheeler', 'Two-Wheeler'), ('other', 'Other')], max_length=20)),
                ('coverage_type', models.CharField(blank=True, choices=[('comprehensive', 'Comprehensive'), ('third_party', 'Third Party'), ('own_damage', 'Own Damage')], max_length=20)),
                ('idv_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('ncb_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('add_on_covers', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policies', to='instruments.account')),
                ('covered_members', models.ManyToManyField(blank=True, related_name='covered_by_policies', to='core.member')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='core.household')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policies', to='core.member')),
                ('vehicle_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_insurance_policies', to='instruments.instrument')),
            ],
            options={
                'ordering': ['policy_type', 'policy_name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('settled', 'Settled')], default='filed', max_length=20)),
                ('settled_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_claims', to='insurance.insurancepolicy')),
            ],
            options={
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePremiumAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('acknowledged_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_acks', to='insurance.insurancepolicy')),
            ],
            options={
                'ordering': ['-due_date'],
                'unique_together': {('policy', 'due_date')},
            },
        ),
    ]
