# Generated by Django 6.0.4 on 2026-04-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='include_in_networth',
            field=models.BooleanField(default=True, help_text="If false, this member's share of holdings/accounts is excluded from household net worth calculations."),
        ),
    ]
