# Generated by Codex on 2026-04-29

from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member_include_in_networth'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('household', 'Household'), ('user', 'User')], default='global', max_length=20)),
                ('value', core.fields.EncryptedTextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='integration_credentials', to='core.household')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='integration_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('key', 'scope', 'household', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='integrationcredential',
            index=models.Index(fields=['key', 'scope'], name='core_integr_key_708abc_idx'),
        ),
    ]

