# Generated by Django 6.0.4 on 2026-05-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_integrationcredential'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='integrationcredential',
            new_name='core_integr_key_7cc8d4_idx',
            old_name='core_integr_key_708abc_idx',
        ),
    ]
