# Generated by Django 6.0.4 on 2026-07-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_integr_key_708abc_idx_core_integr_key_7cc8d4_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.TextField(blank=True, help_text='Data URI (base64) of the member photo, e.g. "data:image/jpeg;base64,...".'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.TextField(blank=True, help_text='Data URI (base64) of the uploaded profile photo; takes precedence over google_picture when set.'),
        ),
    ]
