# Generated by Django 5.2.6 on 2026-08-21 18:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_member_photo_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='risk_free_rate_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.50'), help_text='Used as the risk-free rate in Sharpe ratio calculations (e.g. current 91-day T-bill yield ballpark). Not fetched live — update it yourself periodically.', max_digits=5),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Used to derive age for allocation rule-of-thumb suggestions. Optional.', null=True),
        ),
    ]
