# Generated by Django 6.0.4 on 2026-04-12 15:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tx_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('direction', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=10)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('interest', 'Interest'), ('salary', 'Salary'), ('tax_payment', 'Tax Payment'), ('tax_refund', 'Tax Refund'), ('emi', 'EMI'), ('loan_disbursal', 'Loan Disbursal'), ('premium', 'Insurance Premium'), ('other', 'Other')], max_length=30)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV'), ('api', 'API')], default='manual', max_length=10)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('idempotency_key', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='instruments.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.household')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='instruments.instrument')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.member')),
            ],
            options={
                'ordering': ['tx_date', 'id'],
                'indexes': [models.Index(fields=['household', 'tx_date'], name='ledger_tran_househo_e3c2e9_idx'), models.Index(fields=['account', 'tx_date'], name='ledger_tran_account_526f57_idx'), models.Index(fields=['instrument', 'tx_date'], name='ledger_tran_instrum_bb8705_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('household', 'idempotency_key'), name='uniq_household_idempotency_nonempty')],
            },
        ),
    ]
