# Generated by Django 6.0.4 on 2026-06-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_transaction_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('interest', 'Interest'), ('salary', 'Salary'), ('tax_payment', 'Tax Payment'), ('tax_refund', 'Tax Refund'), ('emi', 'EMI'), ('loan_disbursal', 'Loan Disbursal'), ('premium', 'Insurance Premium'), ('cc_bill_payment', 'CC Bill Payment'), ('other', 'Other')], max_length=30),
        ),
    ]
