# Generated by Django 6.0.4 on 2026-07-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_integr_key_708abc_idx_core_integr_key_7cc8d4_idx'),
        ('ledger', '0004_transaction_enrichment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.household')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='ledger.tag'),
        ),
    ]
