# Generated by Django 6.0.4 on 2026-07-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_tag_transaction_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='affects_balance',
            field=models.BooleanField(default=True, help_text="Whether this transaction is counted toward the linked account's balance. Turn off for transactions recorded against an account that never actually held the money (e.g. NPS contributions debited straight from payroll)."),
        ),
    ]
