# Generated by Django 6.0.4 on 2026-09-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0013_investment'),
        ('ledger', '0006_transaction_affects_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='investment',
            field=models.ForeignKey(blank=True, help_text='Which specific holding under `instrument` this buy is for — set only for equity/mutual-fund instruments where `instrument` is a shared type-level shell. Null for FD/bond/other types, where `instrument` alone identifies the holding.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='instruments.investment'),
        ),
    ]
