# Generated by Django 6.0.4 on 2026-09-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_transaction_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='realized_gain',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Profit/loss locked in by this sale, computed server-side at creation time as sale proceeds minus (average cost per unit × quantity sold) using this holding's net_invested/quantity just before this transaction. Set only for transaction_type=sell; never client-supplied, so it can't drift from the real holding state. Average-cost basis, not FIFO/LIFO lot tracking.", max_digits=18, null=True),
        ),
    ]
