# Generated by Django 6.0.4 on 2026-04-19 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('instruments', '0003_account_balance_cc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('health', 'Health & Medical'), ('shopping', 'Shopping'), ('education', 'Education'), ('rent', 'Rent'), ('emi', 'EMI / Loan Payment'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('for_members', models.ManyToManyField(blank=True, related_name='shared_expenses', to='core.member')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.household')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to='core.member')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='instruments.account')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
