# Generated by Codex on 2026-04-29

from django.db import migrations

import core.fields
from core.crypto import encrypt_str


def _encrypt_existing(apps, schema_editor):
    GoogleCredential = apps.get_model('gmail_ingestion', 'GoogleCredential')
    prefix = core.fields.EncryptedTextField.prefix
    for cred in GoogleCredential.objects.all():
        changed = False
        if cred.refresh_token and not str(cred.refresh_token).startswith(prefix):
            cred.refresh_token = f'{prefix}{encrypt_str(str(cred.refresh_token))}'
            changed = True
        if cred.access_token and not str(cred.access_token).startswith(prefix):
            cred.access_token = f'{prefix}{encrypt_str(str(cred.access_token))}'
            changed = True
        if changed:
            cred.save(update_fields=['refresh_token', 'access_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_ingestion', '0001_initial'),
        ('core', '0004_integrationcredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecredential',
            name='refresh_token',
            field=core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='googlecredential',
            name='access_token',
            field=core.fields.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(_encrypt_existing, migrations.RunPython.noop),
    ]

