# Generated by Django 6.0.4 on 2026-04-30 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_ingestion', '0002_encrypt_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gmailprocessedmessage',
            new_name='gmail_inges_user_id_bbd610_idx',
            old_name='gmail_ingest_user_id_5b2f7d_idx',
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='email',
            field=models.CharField(blank=True, help_text='Google account email, populated after OAuth', max_length=255),
        ),
        migrations.AddField(
            model_name='googlecredential',
            name='label',
            field=models.CharField(blank=True, help_text='User-friendly label, defaults to email', max_length=100),
        ),
        migrations.AlterField(
            model_name='googlecredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
