# Generated by Django 6.0.4 on 2026-05-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_ingestion', '0004_gmailsyncconfig_excluded_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailsyncconfig',
            name='custom_templates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
