# Generated by Django 6.0.4 on 2026-05-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_ingestion', '0005_custom_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailsyncconfig',
            name='excluded_senders',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
