# Generated by Django 6.0.4 on 2026-04-12 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('broker', 'Broker'), ('pf', 'Provident Fund'), ('loan', 'Loan'), ('credit_card', 'Credit Card'), ('insurance', 'Insurance'), ('cash', 'Cash'), ('other', 'Other')], max_length=30)),
                ('institution_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.household')),
                ('primary_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_accounts', to='core.member')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('instrument_type', models.CharField(choices=[('cash', 'Cash'), ('equity', 'Equity'), ('mutual_fund', 'Mutual Fund'), ('sip', 'SIP'), ('fd', 'Fixed Deposit'), ('rd', 'Recurring Deposit'), ('epf', 'EPF'), ('ppf', 'PPF'), ('nps', 'NPS'), ('real_estate', 'Real Estate'), ('gold', 'Gold'), ('vehicle', 'Vehicle'), ('liability', 'Liability'), ('insurance', 'Insurance'), ('other', 'Other')], max_length=30)),
                ('symbol', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_instruments', to='instruments.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='core.household')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AccountOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='instruments.account')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_ownerships', to='core.member')),
            ],
            options={
                'unique_together': {('account', 'member')},
            },
        ),
        migrations.CreateModel(
            name='InstrumentOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_percent', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='instruments.instrument')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instrument_ownerships', to='core.member')),
            ],
            options={
                'unique_together': {('instrument', 'member')},
            },
        ),
    ]
