# Generated by Django 6.0.4 on 2026-04-14 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FDDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('annual_rate', models.DecimalField(decimal_places=4, help_text='Annual interest rate as percentage, e.g. 7.5', max_digits=6)),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('compounding', models.CharField(choices=[('simple', 'Simple Interest'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('annually', 'Annually')], default='quarterly', max_length=20)),
                ('maturity_value', models.DecimalField(blank=True, decimal_places=2, help_text='Bank-stated maturity value if known', max_digits=18, null=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fd_details', to='instruments.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
