# Generated by Django 6.0.4 on 2026-04-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_fddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Credit card spending limit', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Starting balance when this account was added', max_digits=18),
        ),
        migrations.AddField(
            model_name='account',
            name='statement_due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Day of month when credit card bill is due (1-28)', null=True),
        ),
    ]
