# Generated by Django 6.0.4 on 2026-04-22 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('instruments', '0003_account_balance_cc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#94a3b8', help_text='Hex color e.g. #0ea5e9', max_length=7)),
                ('icon_name', models.CharField(blank=True, help_text='Icon key e.g. shield', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='core.household')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='asset_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='instruments.assetcategory'),
        ),
    ]
