# Generated by Django 6.0.4 on 2026-08-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_member_photo_userprofile_photo'),
        ('instruments', '0005_alter_instrument_instrument_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(condition=models.Q(('instrument_type', 'fd'), models.Q(('symbol', ''), _negated=True)), fields=('household', 'symbol'), name='unique_fd_account_number_per_household'),
        ),
    ]
