# Generated by Django 5.2.6 on 2026-08-20 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_member_photo_userprofile_photo'),
        ('instruments', '0006_instrument_unique_fd_account_number_per_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='include_in_rebalancing',
            field=models.BooleanField(default=True, help_text="Uncheck to exclude this holding from allocation targets and rebalancing suggestions (e.g. an emergency-fund FD or an heirloom asset you don't want to rebalance)."),
        ),
        migrations.CreateModel(
            name='MutualFundDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amc', models.CharField(blank=True, max_length=120)),
                ('fund_category', models.CharField(blank=True, help_text='e.g. Equity, Debt, Hybrid', max_length=80)),
                ('fund_sub_category', models.CharField(blank=True, help_text='e.g. Large Cap, Flexi Cap', max_length=80)),
                ('folio_no', models.CharField(blank=True, max_length=60)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mf_details', to='instruments.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllocationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asset_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_targets', to='instruments.assetcategory')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_targets', to='core.household')),
            ],
            options={
                'ordering': ['asset_category__sort_order'],
                'unique_together': {('household', 'asset_category')},
            },
        ),
    ]
