# Generated by Django 5.2.6 on 2026-08-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_backfill_mutualfunddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfunddetails',
            name='expense_ratio',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total expense ratio (TER) as a percentage, e.g. 0.450. From the fund factsheet.', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='FundHoldingsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_date', models.DateField()),
                ('source_url', models.URLField(blank=True, help_text='Where you downloaded this from, for next time.', max_length=500)),
                ('uploaded_file_name', models.CharField(blank=True, max_length=255)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings_snapshots', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-as_of_date'],
                'unique_together': {('instrument', 'as_of_date')},
            },
        ),
        migrations.CreateModel(
            name='FundHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isin', models.CharField(blank=True, max_length=20)),
                ('instrument_name', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('weight_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='instruments.fundholdingssnapshot')),
            ],
            options={
                'ordering': ['-weight_percent'],
            },
        ),
    ]
