# Generated by Django 6.0.4 on 2026-09-07 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0009_mutualfunddetails_expense_ratio_fundholdingssnapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('equity', 'Equity'), ('mutual_fund', 'Mutual Fund'), ('sip', 'SIP'), ('fd', 'Fixed Deposit'), ('rd', 'Recurring Deposit'), ('bond', 'Bond'), ('epf', 'EPF'), ('ppf', 'PPF'), ('nps', 'NPS'), ('real_estate', 'Real Estate'), ('gold', 'Gold'), ('vehicle', 'Vehicle'), ('liability', 'Liability'), ('insurance', 'Insurance'), ('lending', 'Lending (Loan Given)'), ('other', 'Other')], max_length=30),
        ),
        migrations.CreateModel(
            name='BondDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer_name', models.CharField(blank=True, max_length=200)),
                ('bond_type', models.CharField(choices=[('government', 'Government Bond'), ('corporate', 'Corporate Bond'), ('tax_free', 'Tax-Free Bond'), ('sgb', 'Sovereign Gold Bond'), ('ncd', 'NCD'), ('other', 'Other')], default='other', max_length=20)),
                ('isin', models.CharField(blank=True, max_length=20)),
                ('face_value', models.DecimalField(decimal_places=2, help_text='Face value per unit, or total invested amount for a single holding', max_digits=18)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units held, if applicable')),
                ('coupon_rate', models.DecimalField(decimal_places=4, help_text='Annual coupon rate as percentage, e.g. 7.75', max_digits=6)),
                ('coupon_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('annual', 'Annual'), ('cumulative', 'Cumulative (paid at maturity)')], default='annual', max_length=20)),
                ('investment_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('first_coupon_date', models.DateField(blank=True, help_text='First coupon due date, if different from one period after investment_date', null=True)),
                ('grace_days', models.PositiveSmallIntegerField(default=15)),
                ('maturity_value', models.DecimalField(blank=True, decimal_places=2, help_text='Issuer-stated redemption value if known', max_digits=18, null=True)),
                ('credit_rating', models.CharField(blank=True, help_text='e.g. AAA, AA+', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bond_details', to='instruments.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BondCouponAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('acknowledged_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_acks', to='instruments.bonddetails')),
            ],
            options={
                'ordering': ['-due_date'],
                'unique_together': {('bond', 'due_date')},
            },
        ),
    ]
