# Generated by Django 6.0.4 on 2026-09-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0010_alter_instrument_instrument_type_bonddetails_and_more'),
        ('ledger', '0006_transaction_affects_balance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instrument',
            name='unique_fd_account_number_per_household',
        ),
        migrations.AddField(
            model_name='bonddetails',
            name='funding_transaction',
            field=models.OneToOneField(blank=True, help_text='The buy Transaction that funded this bond investment, if recorded through the app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bond_details', to='ledger.transaction'),
        ),
        migrations.AddField(
            model_name='fddetails',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank FD account/receipt number — used to detect a duplicate import of the same deposit.', max_length=60),
        ),
        migrations.AddField(
            model_name='fddetails',
            name='funding_transaction',
            field=models.OneToOneField(blank=True, help_text='The buy/deposit Transaction that funded this FD, if recorded through the app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fd_details', to='ledger.transaction'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('debt', 'Debt'), ('equity', 'Equity'), ('liquid', 'Liquid'), ('retirement', 'Retirement'), ('hybrid', 'Hybrid'), ('gold', 'Gold'), ('real_asset', 'Real Asset'), ('other', 'Other')], help_text='Cross-cutting risk/liquidity classification (e.g. Debt, Equity, Retirement) — independent of instrument_type, so holdings of different types can be grouped together (e.g. FD + EPF + Debt mutual funds all as "Debt").', max_length=20),
        ),
        migrations.AlterField(
            model_name='bonddetails',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bond_details', to='instruments.instrument'),
        ),
        migrations.AlterField(
            model_name='fddetails',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fd_details', to='instruments.instrument'),
        ),
    ]
