# Generated by Django 6.0.4 on 2026-09-08 17:01
"""Backfill FDDetails/BondDetails.funding_transaction and FDDetails.account_number
for existing rows, now that the O2O->FK loosening in the prior migration allows
multiple FD/Bond investments per instrument.

Purely additive/informational: this never creates, modifies, or deletes a
Transaction, FDDetails, or ValuationSnapshot row, and valuation math (which
reads FDDetails.principal/annual_rate/dates directly, never funding_transaction)
is unaffected either way. Rows this migration can't confidently link are left
NULL and logged — safer than guessing against real financial data.
"""
from django.db import migrations


def backfill(apps, schema_editor):
    FDDetails = apps.get_model('instruments', 'FDDetails')
    BondDetails = apps.get_model('instruments', 'BondDetails')
    Transaction = apps.get_model('ledger', 'Transaction')

    unlinked_fd = []
    for fd in FDDetails.objects.select_related('instrument').all():
        if fd.instrument.symbol:
            fd.account_number = fd.instrument.symbol
            fd.save(update_fields=['account_number'])

        txs = list(Transaction.objects.filter(instrument_id=fd.instrument_id).order_by('tx_date', 'id'))
        if len(txs) == 1:
            fd.funding_transaction = txs[0]
            fd.save(update_fields=['funding_transaction'])
        elif len(txs) > 1:
            # Sweep/MOD deposits accumulate multiple transactions over
            # re-imports (sweep transfers) — the earliest one is the original
            # opening deposit.
            fd.funding_transaction = txs[0]
            fd.save(update_fields=['funding_transaction'])
        else:
            unlinked_fd.append(fd.instrument.name)

    unlinked_bond = []
    for bond in BondDetails.objects.select_related('instrument').all():
        txs = list(Transaction.objects.filter(instrument_id=bond.instrument_id).order_by('tx_date', 'id'))
        if len(txs) >= 1:
            bond.funding_transaction = txs[0]
            bond.save(update_fields=['funding_transaction'])
        else:
            unlinked_bond.append(bond.instrument.name)

    if unlinked_fd:
        print(f'\n  [backfill] {len(unlinked_fd)} FD(s) with no funding transaction found (left unlinked): {unlinked_fd}')
    if unlinked_bond:
        print(f'  [backfill] {len(unlinked_bond)} Bond(s) with no funding transaction found (left unlinked): {unlinked_bond}')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0011_remove_instrument_unique_fd_account_number_per_household_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill, noop_reverse),
    ]
