# Generated by Django 6.0.4 on 2026-09-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_household_risk_free_rate_percent_and_more'),
        ('instruments', '0012_backfill_fd_bond_funding_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. company/ticker name for equity, scheme name for a fund', max_length=200)),
                ('symbol', models.CharField(blank=True, help_text='Ticker (equity) or AMFI code (mutual fund)', max_length=32)),
                ('isin', models.CharField(blank=True, max_length=20)),
                ('folio_no', models.CharField(blank=True, help_text='Mutual fund folio number', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='instruments.instrument')),
                ('member', models.ForeignKey(blank=True, help_text='Who owns this specific holding — the per-holding equivalent of InstrumentOwnership.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='core.member')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('instrument', 'name', 'folio_no')},
            },
        ),
    ]
