# Generated by Django 6.0.4 on 2026-09-09 16:08, reordered by hand: the
# original autodetected migration removed MutualFundDetails.instrument/
# folio_no before anything could read them to populate the new `investment`
# FK — that would have silently discarded the 44 real MutualFundDetails
# rows this household has. AddField is split out first, a RunPython data
# migration in 0015 does the actual Instrument->Investment collapse and
# backfill, and the RemoveField operations for mutualfunddetails move to
# 0016 (after 0015 has safely read everything it needs).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0013_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfunddetails',
            name='investment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mf_details', to='instruments.investment'),
        ),
        migrations.AddField(
            model_name='fundholdingssnapshot',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holdings_snapshots', to='instruments.investment'),
        ),
    ]
