# Generated by Django 6.0.4 on 2026-09-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_household_risk_free_rate_percent_and_more'),
        ('instruments', '0016_finalize_mf_investment_schema'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('instrument', 'name', 'folio_no', 'member')},
        ),
    ]
