# Generated by Django 6.0.4 on 2026-10-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0018_split_shared_equity_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sms_identifiers',
            field=models.CharField(blank=True, help_text='Trailing digits of this account and its cards as they appear in bank SMS, comma-separated (e.g. "3422, 2133"). Used to match SMS alerts to this account; learned automatically when you approve an SMS.', max_length=200),
        ),
    ]
