# Generated by Django 6.0.4 on 2026-10-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0019_account_sms_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='market_cap',
            field=models.CharField(blank=True, choices=[('large_cap', 'Large Cap'), ('mid_cap', 'Mid Cap'), ('small_cap', 'Small Cap')], help_text='Stock/ETF market-cap sub-category (SEBI: top 100 large, 101–250 mid, rest small). Set automatically from NSE index lists — see fund_data/market_cap.py.', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='market_cap_auto',
            field=models.BooleanField(default=True, help_text='False once the user sets market_cap by hand, so refreshes leave it alone.'),
        ),
    ]
