# Generated by Django 6.0.4 on 2026-10-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0021_equity_shell_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='asset_category',
            field=models.ForeignKey(blank=True, help_text="Overrides the instrument's category for this holding when set.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='instruments.assetcategory'),
        ),
        migrations.AddField(
            model_name='investment',
            name='category_auto',
            field=models.BooleanField(default=True, help_text='False once the user picks the category by hand, so refreshes leave it alone.'),
        ),
    ]
