# Generated by Django 6.0.4 on 2026-10-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0022_investment_asset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('equity', 'Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual Fund'), ('sip', 'SIP'), ('fd', 'Fixed Deposit'), ('rd', 'Recurring Deposit'), ('bond', 'Bond'), ('epf', 'EPF'), ('ppf', 'PPF'), ('nps', 'NPS'), ('real_estate', 'Real Estate'), ('gold', 'Gold'), ('vehicle', 'Vehicle'), ('liability', 'Liability'), ('insurance', 'Insurance'), ('lending', 'Lending (Loan Given)'), ('other', 'Other')], max_length=30),
        ),
    ]
