# Generated by Django 6.0.4 on 2026-04-22 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('instruments', '0004_assetcategory_instrument_asset_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorthTreeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_date', models.DateField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networth_tree_snapshots', to='core.household')),
            ],
            options={
                'ordering': ['-as_of_date', '-id'],
                'unique_together': {('household', 'as_of_date')},
            },
        ),
        migrations.CreateModel(
            name='NetWorthTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('kind', models.CharField(choices=[('linked_category', 'Linked Category'), ('linked_instrument', 'Linked Instrument'), ('manual_branch', 'Manual Branch'), ('manual_item', 'Manual Item')], max_length=24)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('current_value_override', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_collapsed', models.BooleanField(default=False)),
                ('linked_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='networth_tree_nodes', to='instruments.assetcategory')),
                ('linked_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='networth_tree_nodes', to='instruments.instrument')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='networth_tree.networthtreenode')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='networth_tree.networthtreesnapshot')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['snapshot', 'parent', 'sort_order'], name='networth_tr_snapsho_5f52a5_idx'), models.Index(fields=['snapshot', 'kind'], name='networth_tr_snapsho_d6fcf5_idx')],
            },
        ),
    ]
