# Generated by Django 5.2.6 on 2026-08-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0009_mutualfunddetails_expense_ratio_fundholdingssnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. "Nifty 50 (via UTI Nifty 50 Index Fund)"', max_length=120)),
                ('mfapi_scheme_code', models.CharField(max_length=20, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mfapi_scheme_code', models.CharField(max_length=20, unique=True)),
                ('scheme_name', models.CharField(help_text='As returned by mfapi.in, for display/debugging mismatches.', max_length=255)),
                ('fund_house', models.CharField(blank=True, max_length=120)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_fund', to='instruments.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BenchmarkFundNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nav_date', models.DateField()),
                ('nav', models.DecimalField(decimal_places=4, max_digits=14)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='fund_data.benchmarkfund')),
            ],
            options={
                'ordering': ['nav_date'],
                'indexes': [models.Index(fields=['benchmark', 'nav_date'], name='fund_data_b_benchma_013322_idx')],
                'unique_together': {('benchmark', 'nav_date')},
            },
        ),
        migrations.CreateModel(
            name='ExternalFundNav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nav_date', models.DateField()),
                ('nav', models.DecimalField(decimal_places=4, max_digits=14)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_history', to='fund_data.externalfund')),
            ],
            options={
                'ordering': ['nav_date'],
                'indexes': [models.Index(fields=['fund', 'nav_date'], name='fund_data_e_fund_id_8842f9_idx')],
                'unique_together': {('fund', 'nav_date')},
            },
        ),
    ]
