# Generated by Django 6.0.4 on 2026-08-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_data', '0002_seed_benchmark_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarkfund',
            name='category_match',
            field=models.CharField(blank=True, choices=[('large_cap', 'Large Cap'), ('mid_cap', 'Mid Cap'), ('small_cap', 'Small Cap'), ('flexi_cap_broad_market', 'Flexi Cap / Broad Market')], max_length=30),
        ),
    ]
