# Generated by Django 6.0.4 on 2026-09-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_data', '0004_seed_category_benchmarks'),
        ('instruments', '0014_alter_fundholdingssnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalfund',
            name='instrument',
        ),
        migrations.AddField(
            model_name='externalfund',
            name='investment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_fund', to='instruments.investment'),
        ),
    ]
