# Generated by Django 6.0.4 on 2026-10-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund_data', '0005_remove_externalfund_instrument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalfund',
            name='mfapi_scheme_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
