# Generated by Django 6.0.4 on 2026-04-12 15:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valuation_date', models.DateField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv', 'CSV'), ('api', 'API')], default='manual', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valuation_snapshots', to='instruments.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='core.household')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valuation_snapshots', to='instruments.instrument')),
            ],
            options={
                'ordering': ['-valuation_date', '-id'],
                'indexes': [models.Index(fields=['household', 'valuation_date'], name='valuations__househo_e27fbd_idx'), models.Index(fields=['instrument', 'valuation_date'], name='valuations__instrum_bbcd02_idx'), models.Index(fields=['account', 'valuation_date'], name='valuations__account_8fc47b_idx')],
            },
        ),
    ]
