# Generated by Django 6.0.4 on 2026-04-14 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('valuations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField()),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networth_snapshots', to='core.household')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('household', 'snapshot_date')},
            },
        ),
    ]
