# Generated by Django 6.0.4 on 2026-09-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_household_risk_free_rate_percent_and_more'),
        ('instruments', '0013_investment'),
        ('valuations', '0002_networthsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationsnapshot',
            name='investment',
            field=models.ForeignKey(blank=True, help_text='Which specific holding under `instrument` this snapshot values — set only for equity/mutual-fund instruments where `instrument` is a shared type-level shell.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valuation_snapshots', to='instruments.investment'),
        ),
        migrations.AddIndex(
            model_name='valuationsnapshot',
            index=models.Index(fields=['investment', 'valuation_date'], name='valuations__investm_b3f87c_idx'),
        ),
    ]
