# Generated by Django 6.0.4 on 2026-04-12 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIPMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('due_day', models.PositiveSmallIntegerField(default=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grace_days', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip_mandates', to='instruments.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip_mandates', to='core.household')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sip_mandates', to='instruments.instrument')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sip_mandates', to='core.member')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
