# Generated by Django 6.0.4 on 2026-04-29 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIPPaymentAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('acknowledged_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_acks', to='alerts.sipmandate')),
            ],
            options={
                'ordering': ['-due_date'],
                'unique_together': {('mandate', 'due_date')},
            },
        ),
    ]
