# Generated by Django 6.0.4 on 2026-07-02 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_sippaymentack'),
        ('core', '0005_rename_core_integr_key_708abc_idx_core_integr_key_7cc8d4_idx'),
        ('instruments', '0005_alter_instrument_instrument_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('due_day', models.PositiveSmallIntegerField(default=5)),
                ('start_date', models.DateField()),
                ('tenure_months', models.PositiveSmallIntegerField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('grace_days', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_mandates', to='instruments.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_mandates', to='core.household')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rd_mandates', to='instruments.instrument')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rd_mandates', to='core.member')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RDPaymentAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('acknowledged_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_acks', to='alerts.rdmandate')),
            ],
            options={
                'ordering': ['-due_date'],
                'unique_together': {('mandate', 'due_date')},
            },
        ),
    ]
