# Generated by Django 6.0.4 on 2026-06-17 19:18

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_rename_core_integr_key_708abc_idx_core_integr_key_7cc8d4_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstoxCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upstox_user_id', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('access_token', core.fields.EncryptedTextField(blank=True)),
                ('refresh_token', core.fields.EncryptedTextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, help_text='Household member whose Upstox account this is', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upstox_credentials', to='core.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstox_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
