# Generated by Django 6.0.4 on 2026-08-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_household_risk_free_rate_percent_and_more'),
        ('instruments', '0009_mutualfunddetails_expense_ratio_fundholdingssnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.CharField(choices=[('equity', 'Equity'), ('debt', 'Debt'), ('hybrid', 'Hybrid')], max_length=20)),
                ('rule_60_40_category', models.CharField(choices=[('growth', 'Growth (60%)'), ('stability', 'Stability (40%)')], max_length=20)),
                ('reasoning', models.TextField(blank=True)),
                ('model_used', models.CharField(max_length=60)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_classification', to='instruments.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundReturnsComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('input_snapshot', models.JSONField(help_text='The exact XIRR/expense-ratio figures sent to Claude, for auditability.')),
                ('model_used', models.CharField(max_length=60)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_returns_comparison', to='instruments.instrument')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RebalancingExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of_date', models.DateField()),
                ('explanation', models.TextField()),
                ('input_snapshot', models.JSONField(help_text='The compute_rebalancing() rows sent to Claude, for auditability.')),
                ('model_used', models.CharField(max_length=60)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_rebalancing_explanations', to='core.household')),
            ],
            options={
                'unique_together': {('household', 'as_of_date')},
            },
        ),
    ]
