# Generated by Django 6.0.4 on 2026-08-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundreturnscomparison',
            name='input_snapshot',
            field=models.JSONField(help_text='The exact XIRR/expense-ratio figures sent to Gemini, for auditability.'),
        ),
        migrations.AlterField(
            model_name='rebalancingexplanation',
            name='input_snapshot',
            field=models.JSONField(help_text='The compute_rebalancing() rows sent to Gemini, for auditability.'),
        ),
    ]
