# Generated by Django 6.0.4 on 2026-09-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0002_alter_fundreturnscomparison_input_snapshot_and_more'),
        ('instruments', '0014_alter_fundholdingssnapshot_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundclassification',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='fundreturnscomparison',
            name='instrument',
        ),
        migrations.AddField(
            model_name='fundclassification',
            name='investment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_classification', to='instruments.investment'),
        ),
        migrations.AddField(
            model_name='fundreturnscomparison',
            name='investment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_returns_comparison', to='instruments.investment'),
        ),
    ]
