# Generated by Django 6.0.4 on 2026-06-07 14:56

import django.db.models.deletion
import sms_ingestion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_rename_core_integr_key_708abc_idx_core_integr_key_7cc8d4_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text='Friendly name, e.g. "Dad\'s Phone"', max_length=100)),
                ('token', models.CharField(default=sms_ingestion.models._generate_token, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_api_keys', to='core.household')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(max_length=64)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('imported_transaction_id', models.IntegerField(blank=True, null=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='sms_ingestion.smsapikey')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='core.household')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='core.member')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['household', 'status'], name='sms_ingesti_househo_540822_idx')],
                'unique_together': {('household', 'sender', 'received_at', 'body')},
            },
        ),
    ]
