# Generated by Django 6.0.4 on 2026-06-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='template_key',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
