# Generated by Django 6.0.4 on 2026-06-09 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_integr_key_708abc_idx_core_integr_key_7cc8d4_idx'),
        ('instruments', '0004_assetcategory_instrument_asset_category'),
        ('sms_ingestion', '0002_smsmessage_confidence_smsmessage_template_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Lower value = evaluated first')),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('direction', models.CharField(blank=True, max_length=10)),
                ('transaction_type', models.CharField(blank=True, max_length=30)),
                ('classification', models.CharField(blank=True, max_length=20)),
                ('spend_category', models.CharField(blank=True, max_length=30)),
                ('amount_regex', models.CharField(blank=True, max_length=300)),
                ('merchant_regex', models.CharField(blank=True, max_length=300)),
                ('reference_regex', models.CharField(blank=True, max_length=300)),
                ('notes_regex', models.CharField(blank=True, max_length=300)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_rules', to='core.household')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_rules', to='core.member')),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
