# Generated by Django 6.0.4 on 2026-06-09 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_integr_key_708abc_idx_core_integr_key_7cc8d4_idx'),
        ('instruments', '0004_assetcategory_instrument_asset_category'),
        ('sms_ingestion', '0003_smsrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsApprovalObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(db_index=True, max_length=64)),
                ('direction', models.CharField(blank=True, max_length=10)),
                ('classification', models.CharField(blank=True, max_length=20)),
                ('spend_category', models.CharField(blank=True, max_length=30)),
                ('transaction_type', models.CharField(blank=True, max_length=30)),
                ('body_sample', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_observations', to='core.household')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_observations', to='core.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsRuleSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(max_length=64)),
                ('observation_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('accepted', 'Accepted')], db_index=True, default='pending', max_length=20)),
                ('direction', models.CharField(blank=True, max_length=10)),
                ('classification', models.CharField(blank=True, max_length=20)),
                ('spend_category', models.CharField(blank=True, max_length=30)),
                ('transaction_type', models.CharField(blank=True, max_length=30)),
                ('body_samples', models.JSONField(blank=True, default=list)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_suggestions', to='core.household')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_suggestions', to='core.member')),
            ],
            options={
                'ordering': ['-observation_count', '-created_at'],
                'unique_together': {('household', 'sender')},
            },
        ),
    ]
