# Generated by Django 6.0.4 on 2026-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_core_integr_key_708abc_idx_core_integr_key_7cc8d4_idx'),
        ('sms_ingestion', '0004_smsapprovalobservation_smsrulesuggestion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smsmessage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='smsmessage',
            unique_together={('household', 'sender', 'received_at', 'body', 'device_id')},
        ),
    ]
