export const TERMS = {
  simple: {
    holdings: 'Investments',
    instruments: 'Investment Types',
    ledger: 'Transaction History',
    portfolio: 'Investments',
    valuation: 'Account Values',
    xirr: 'Annual Return',
    allocation: 'Distribution',
    instrument: 'Investment',
    asset_category: 'Category',
    nav: 'Price Per Unit',
    unrealized_gain: 'Current Profit',
    realized_gain: 'Profit from Sales',
    expense: 'Spending',
    cashflow: 'Money Flow',
    sip: 'Auto Investment',
    fd: 'Fixed Deposit',
    mandate: 'Auto Investment Plan',
    liabilities: 'Money You Owe',
    accounts: 'My Money',
    alerts: 'Bills & Auto Investments',
    net_worth: 'Total Wealth',
    income: 'Money In',
    spending: 'Money Out',
    savings_rate: 'Savings Rate',
    household: 'Household',
    tax: 'Tax',
    insurance: 'Insurance',
    import: 'Import',
    settings: 'Settings',
    maintenance: 'Maintenance',
    spend_trends: 'Spending Trends',
    cash_flow: 'Money Flow',
  },
  advanced: {
    holdings: 'Holdings',
    instruments: 'Instruments',
    ledger: 'Ledger',
    portfolio: 'Portfolio',
    valuation: 'Valuation',
    xirr: 'XIRR',
    allocation: 'Allocation',
    instrument: 'Instrument',
    asset_category: 'Asset Category',
    nav: 'NAV',
    unrealized_gain: 'Unrealized Gain',
    realized_gain: 'Realized Gain',
    expense: 'Expense',
    cashflow: 'Cash Flow',
    sip: 'SIP',
    fd: 'Fixed Deposit',
    mandate: 'SIP Mandate',
    liabilities: 'Liabilities',
    accounts: 'Accounts',
    alerts: 'Alerts',
    net_worth: 'Net Worth',
    income: 'Income',
    spending: 'Expenses',
    savings_rate: 'Savings Rate',
    household: 'Household',
    tax: 'Tax',
    insurance: 'Insurance',
    import: 'Import',
    settings: 'Settings',
    maintenance: 'Maintenance',
    spend_trends: 'Spend Trends',
    cash_flow: 'Cash Flow',
  },
} as const

export type Mode = 'simple' | 'advanced'
export type TermKey = keyof typeof TERMS.simple
